### ISSUE TITLE
RcppProgress removed from CRAN

### ISSUE THREAD

**Issue by kasperwelbers** [kforner/rcpp_progress#20]
I was surprised to find that RcppProgress was removed from CRAN:

https://cran.r-project.org/web/packages/RcppProgress/index.html

Is there a reason for this, and will it be back?

**Comment by kforner** [comment]
Is it ? There was a warning from the CRAN about something to fix but I did not find the time to do it yet. It's probably related. I'll look into into it ASAP

**Comment by kasperwelbers** [comment]
Ah right, I received the same message. There was some stuff about minor gcc warnings that were no longer tollerated. Seems they were serious about that.

**Comment by kforner** [comment]
FYI: I just resubmitted to the CRAN.

**Comment by kasperwelbers** [comment]
Great, thanks! And in general thanks for this package.

For reference, when I posted this issue yesterday I did get the message from CRAN that it was already archived, but it seems they put it back up for a little while longer (probably because of the reverse dependencies). Anyway, nice that is has been fixed already.

**Comment by mlysy** [comment]
Hi @kforner, as an author of a dependent package I also got the message, and took the liberty of inspecting the CRAN [check results](https://cran.r-project.org/web/checks/check_results_RcppProgress.html).  Looks pretty uninformative to me...did you manage to track down the issue?  Otherwise, I fear the package will just get archived again...

If I may suggest, a very quick hack would be to put [`skip_on_cran()`](http://r-pkgs.had.co.nz/tests.html#test-cran) in each `test_that` block so as to only run tests locally, i.e., not on CRAN.

**Comment by kforner** [comment]
@mlysy 
> did you manage to track down the issue?

Yes. when running tests, devtools::load_all process the source example packages in place, so it tries to compile the C code and store the resulting object files inside the installed package.

**Comment by kforner** [comment]
v0.4.1 in CRAN !
