### ISSUE TITLE
TODO: register native routines

### ISSUE THREAD

**Issue by kforner** [kforner/rcpp_progress#9]
```
* checking compiled code ... NOTE
File ‘RcppProgress/libs/RcppProgress.so’:
  Found no calls to: ‘R_registerRoutines’, ‘R_useDynamicSymbols’
It is good practice to register native routines and to disable symbol
search.
```

**Comment by twolodzko** [comment]
Correct me if I'm wrong, but since your package does not export anything to R, you don't need to register anything. The functions that are exported need to be registered, but Rcpp will deal with that automatically in most cases. So if a package uses RcppProgress, then it needs to register it's stuff, but RcppProgress itself has nothing to register. You probably can ignore the warning.

**Comment by kforner** [comment]
I haven't taken time to dig about this, so I don't know. But there 2 test functions in the .so, and I suppose the check note is about this. I could either register these routines, or put the tests in their own sample package.

**Comment by kforner** [comment]
not needed anymore since RcppProgress does not need a shared library anymore.
